[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dog_spotter_ai"
version = "0.0.1"
description = "\ud83d\udc29\ud83d\udc29\ud83d\udc29 \u72ac\u3092\u8b58\u5225\u3059\u308bAI\uff01"
authors = [
  { name = "osawa-koki" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.12"

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.ruff.lint.isort]
known_first_party = ["dog_spotter_ai"]
force_sort_within_sections = true
